# Generated by Django 2.2.1 on 2019-05-25 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('found_place', models.CharField(choices=[('경', '경영관'), ('광', '광복관'), ('공', '공학원'), ('공A', '제1공학관'), ('공B', '제2공학관'), ('공C', '제3공학관'), ('백양', '백양관'), ('백주', '백주년기념관'), ('빌', '빌링슬리관'), ('스', '스팀슨관'), ('과', '과학관'), ('백양누리', '백양누리'), ('학', '학생회관'), ('대', '대강당'), ('대우', '대우관'), ('음', '음악관'), ('체', '체육관'), ('스', '스포츠과학관'), ('중', '중앙도서관'), ('학술정보원', '학술정보원'), ('과학원', '과학원'), ('삼', '삼성관'), ('청', '청송대'), ('상남', '상남경영원'), ('알', '알렌관'), ('언', '언더우드관'), ('아펜', '아펜젤러관'), ('성', '성암관'), ('연', '연희관'), ('한', '한경관'), ('신', '신학관'), ('외', '외솔관'), ('교', '교육과학관'), ('위', '위당관'), ('미', '미우관'), ('무1', '무악1학사'), ('무2', '무악2학사'), ('무3', '무악3학사'), ('무4', '무악4학사'), ('운동', '운동선수기숙사'), ('우', '우정원')], default='경', max_length=10)),
                ('kept_place', models.CharField(choices=[('경', '경영관'), ('광', '광복관'), ('공', '공학원'), ('공A', '제1공학관'), ('공B', '제2공학관'), ('공C', '제3공학관'), ('백양', '백양관'), ('백주', '백주년기념관'), ('빌', '빌링슬리관'), ('스', '스팀슨관'), ('과', '과학관'), ('백양누리', '백양누리'), ('학', '학생회관'), ('대', '대강당'), ('대우', '대우관'), ('음', '음악관'), ('체', '체육관'), ('스', '스포츠과학관'), ('중', '중앙도서관'), ('학술정보원', '학술정보원'), ('과학원', '과학원'), ('삼', '삼성관'), ('청', '청송대'), ('상남', '상남경영원'), ('알', '알렌관'), ('언', '언더우드관'), ('아펜', '아펜젤러관'), ('성', '성암관'), ('연', '연희관'), ('한', '한경관'), ('신', '신학관'), ('외', '외솔관'), ('교', '교육과학관'), ('위', '위당관'), ('미', '미우관'), ('무1', '무악1학사'), ('무2', '무악2학사'), ('무3', '무악3학사'), ('무4', '무악4학사'), ('운동', '운동선수기숙사'), ('우', '우정원')], default='경', max_length=10)),
                ('item_type', models.CharField(choices=[('필', '필기류'), ('지', '지갑'), ('전', '전자기기'), ('의', '의류'), ('신', '신분증/카드'), ('기', '기타')], default='필', max_length=10)),
                ('found_date', models.DateField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Post')),
            ],
        ),
    ]
